const products = [
    {id:'1', title: 'Coleccion Harry Potter', author: 'J.K. Rowling', category: 'Literatura', price: 193.50 , stock:50, description: 'La colección completa de Harry Potter en un estuche que reúne las siete novelas de la saga más mágica de todos los tiempos.', imageUrl:'/src/assets/literatura1.png'},
    {id:'2', title: 'Una lata en el bosque', author: 'Susanna Isern Iñigo', category: 'Infantil', price: 17.90, stock:30, description: 'Marina camina por el bosque, las hojas tostadas crujen a su paso. De pronto mete el pie en un objeto duro y cortante. ¡Es una lata de metal! Y, por si fuera poco, se ha quedado atascada. Por suerte un grupo de animalillos del bosque acude a su rescate. Marina, Jorge, Niam, Toni, Liz, todos ellos son protagonistas de trece historias encadenadas por la empatía donde será necesario entender los sentimientos de los demás.', imageUrl:'/src/assets/infantil1.jpg'},
    {id:'3', title: 'La era de La inteligencia artificial', author: 'Henry Kissinger, Eric Schmidt, Daniel Huttenlocher', category: 'Ciencia', price: 25.95, stock:40, description: 'Una IA aprendió a ganar al ajedrez realizando jugadas que los grandes maestros nunca habían concebido. Otra IA descubrió un nuevo antibiótico analizando propiedades moleculares que los científicos no comprendían. Aviones propulsados por IA están derrotando a experimentados pilotos en combates aéreos simulados. La IA está irrumpiendo en la investigación, la transmisión en directo o streaming, la medicina, la educación y muchos otros campos y, al hacerlo, está transformando la forma en que los humanos experimentan la realidad.La era de la Inteligencia Artificial es una hoja de ruta esencial para nuestro presente y nuestro futuro, una era distinta a todas las anteriores.', imageUrl:'/src/assets/ciencia1.jpg'},
    {id:'4', title: 'Paseos por Fez', author: 'Aziza Benani', category: 'Viajes', price: 19.00, stock:20, description: 'Marc de Mazières pertenece a una familia de famosos arquitectos en Marruecos; aunque no era conocido por su faceta de escritor, también compartía esta afición. Su actividad como presidente de la "Fédération des Syndicats Initiative" en Marruecos, le ofreció la oportunidad de conocer el país, conocimiento patente en tres obras suyas: Les kasbas du Haut Atlas (1932), Promenades à Fès (1933) y Promenades à Marrakech (1937) Por lo que se refiere a la presente obra, es evidente que no es fruto de la sola observación de la estancia del autor en Fez; también se nutre de lecturas eruditas previas, cuyas referencias abundan en Promenades à Fès. Se trata de autores árabes, españoles y franceses de diferentes épocas: el-Bekri, Ibn Abi Zara el Fesi, León el Africano, Mármol y Carvajal, Pierre Loti, Maurice le Glay, Gómez Carrillo, etc. A veces dichas lecturas parecen interponerse entre él y la realidad. Así pues, de Mazières relata con mucha precisión los usos y costumbres de Fez y no escatima detalles en sus descripciones y comentarios. Evoca la diversidad de la población activa y productiva, así como las élites', imageUrl:'/src/assets/viajes1.jpg'},
    {id:'5', title: 'One piece estampida', author: 'Eiichiro oda', category: 'Anime', price: 10.50 , stock:50, description: 'Sé testigo de una batalla campal entre piratas, marines, los Siete Señores de la Guerra y el Ejército Revolucionario con motivo del Festival de los Piratas.', imageUrl:'/src/assets/anime1.jpg'}
  ]


export const mFetch = (id) => {
  
  return new Promise ( (res, rej) => {
    setTimeout(()=> {
        res(id ? products.find(prod =>prod.id ===id) :products)
    }, 100)
  })
}
